### ISSUE TITLE
AeadCipher::seal_to implementation copies plaintext into output buffer before error checks

### ISSUE THREAD

**Issue by str4d** [KizzyCode/crypto_api_chachapoly#4]
The `AeadCipher::seal` API mutates the provided plaintext buffer to encrypt in-place, after performing various error checks. If the caller ignores the return value (and thus any errors), the plaintext will end up being used unencrypted. This is inherent in the design of the API, so it's a risk that the caller is clearly signing up to.

The `AeadCipher::seal_to` API provides an interface for interacting with an AEAD that ostensibly encrypts from one buffer into another, according to its documentation:

> AEAD-seals `plaintext` into `buf` together with `ad` using `key` and `nonce` and returns the ciphertext length

Thus a caller could reasonably assume that if they ignored the return value, the output buffer would be unmodified, and the plaintext would not leak. However, the implementation of `AeadCipher::seal_to` for `ChachaPolyIetf` copies the plaintext into the output buffer and then calls `AeadCipher::seal` internally, breaking this assumption.

This could be addressed by copying the logic from `seal` into `seal_to`, so that all error checks are performed first, and the encryption operation is guaranteed to succeed at the time the plaintext is copied into the output buffer.

Originally raised by @daira [here](https://github.com/zcash/librustzcash/pull/69#discussion_r290236662).

**Comment by KizzyCode** [comment]
Fixed in https://github.com/KizzyCode/crypto_api_chachapoly/commit/952b5951940ff5d98b89e00540b1c496934fb004
